### ISSUE TITLE
About enchanting .md with complex, custom syntax

### ISSUE THREAD

**Issue by operatino** [livingstyleguide/livingstyleguide#108]
Hi,

I am the founder and maintainer of [SourceJS](http://sourcejs.com) Living Style guide engine, based on JavaScript (NodeJS and client). 

I like growing topic around Living Style guides and keep monitoring other projects, like yours. I really like the simplicity that Markdown documentation offers, but the more it grows with features, the more complex it becomes. I would like to discuss some concerns about complex `.md` files:

1. How does the community likes the ides of writing HTML in Markdown files?
2. Do you really want to add more complexity in `.md` and re-invent html, coding new features like style injection and templates call with custom data to Style Guide page from Markdown?

```
@css {
  .header { background: $my-blue; }}
```

```
@mustache
@template _hello-world.template
@data {
  "name": "Homer",
  "text": "Lorem ipsum"
}
```

(Examples taken from blog post about new feature of LS gem http://www.hagenburger.net/BLOG/livingstyleguide-2.html)

3. Don't you see any limitation about this approach? It is not flexible, it requires to code all the features from scratch and forces to learn new syntax. Then, you will need to support all the issues with this custom syntax, instead of focusing on more important features.
4. Maybe it's better to stick to native JS and HTML way of importing CSS, templates and passing data to them?

In SourceJS we started from the opposite, using flexible web technologies (HTML, JS), and adding some sugar on top of them. As I said, I like simplicity of Markdown, but I'm afraid that building something on this base will eventually lead to bigger problems.

**Comment by hagenburger** [comment]
Hey Robert! Thanks for opening the discussion :)

> How does the community likes the ides of writing HTML in Markdown files?

* I love and prefer it over writing HTML. Also I think HTML examples are more easy to read within Markdown than within other surrounding HTML

> Do you really want to add more complexity in .md and re-invent html, coding new features like style injection and templates call with custom data to Style Guide page from Markdown?

* I want to keep Markdown as “normal” as possible. Most enhancements are made by default values. Usually only about 10 % of my HTML examples require extra non-Markdown code.
* Injecting CSS is one of the features I need the most for my projects. I can’t wait till it’s done. A lot of times I need to slightly modify examples. For example [add some color to explain](https://www.homify.de/assets/styleguide.html#columns) it in the style guide (you can see an ugly quick fix in the linked example which can be avoided by automatisation; also by using the CSS/Sass injection I can access the variables defined in my project and style the style guide in the same way); [add height to examples that are positioned absolute](https://github.com/hagenburger/livingstyleguide-concept/blob/master/c_new-multiple-pages-v2.0x/atoms/_popup.lsg), …

> Don't you see any limitation about this approach? It is not flexible, it requires to code all the features from scratch and forces to learn new syntax. Then, you will need to support all the issues with this custom syntax, instead of focusing on more important features.

* I agree on the Syntax. I want to have it as close to Sass as possible. Right now you may need to learn two new syntaxes filters and YAML for configuration. I’ve you’re not used to YAML, especially writing HTML is tricky. That’s why I’m working on unifying the syntax in a Sass-like style.
* For me it is flexible. As long as you can code Ruby, it’s easy to extend. I already have an idea how to enable JavaScript filters later on. But most functionality needed should be included by default. It is flexible as it allows to have access to Sass variables, mixins, …, or maybe template helpers (Rails).
* In older versions I did not use the `@filter` syntax. That way the only chance was changing the code block language (`~~~ haml-example` just as [Hologram is using it by now](https://github.com/trulia/hologram#tabular-layout-for-component-documentation)). There has been no flexibility besides switching from HTML to Haml. Very often I had more than one special use case per example. So I came up with the filters. They are inspired by Cucumber as well as other inline documentation tools.
* Another issue is generating automated IDs. Doing this by hand is a mess. When I write forms and need to cope and change another example between example 3 and 4, I need to think about renaming all IDs from labels and fields. Automatically scoping IDs with in examples would make live way more easy.
* Automated integration of template languages is very important from my point of view. It is way more easy to split between the visual front-end developer and the application developer.
* What are more important features for you?

> Maybe it's better to stick to native JS and HTML way of importing CSS, templates and passing data to them?

* It’s a personal choice. I wrote all of this because I want as many things to be automated as possible and don’t repeat myself. By the amount of style guides I created so far I might not have saved more time than writing them in plain HTML. But I had way more fun doing so. And every new project inherits the work I did before. And hopefully other people saved time :)

At the end, a style guide should also be entertaining. It is a good (and often the only) way to show your quality work to the outside. This often helps for recruitment. Having little helpers and automation makes it more easy to create a style guide that matches your project.

**Comment by RalphAtHamburg** [comment]
Hi Robert! 

>    How does the community likes the ides of writing HTML in Markdown files?

I prefer writing the styleguide in markdown files. For me the style guide is a documentation which consists more of pretty formatted text, than of big HTML chunks. Think of a typical section within the style guide which describes a module. It has a header, some description, instructions how to use it and a small snippet HTML code to see how it works as well as the output from the HTML snippet. This is how the typical docs for twitter bootstrap or zurb foundation look like. For this approach a markdown document is much more readable than wrapping all in a HTML document.

**Comment by operatino** [comment]
@hagenburger 
Thanks for extensive answer, I like your points and the approach in general. 

Few more questions:
1. I didn't checked yet, do you build your Style Guides to static files and then run them in browser, or it's done dynamically on request?
2. Do you develop new components directly in the documentation, or you just move your examples there after development?
3. How mony Style Guides have you developed?
4. And do you combine few component libraries in one space within your environment. For example web studio could have many projects at a same time.

We chose basic HTML over markdown first, because we develop all the components in the Spec files (documentation files). It's easier having normal syntax highlighting for HTML in our Specs.

Probably I will consider adding alternative syntax to [SourceJS](http://sourcejs.com), Would be great if you will consider making your Markdown parser as a standalone module, that generated JSON, so we could share some of our technologies.

Btw, do you have any plans visiting Amsterdam? I would love to discuss more about Living Style guide topic.

**Comment by operatino** [comment]
@RalphAtHamburg, depends on chosen style of documentation, if you write text mostly then sure, Markdown is a better choice. But if you more focus on development in the documentation and making more examples with different data, then you have more code than text.
